import Foundation

struct InspectorExporter {

    static func shareExport(
        networkEntries: [NetworkEntry],
        logEntries: [LogEntry],
        deeplinkEntries: [DeeplinkEntry],
        onPhaseChange: @MainActor @Sendable @escaping (ExportPhase) -> Void
    ) async -> URL? {
        let content = await buildMarkdown(
            networkEntries: networkEntries,
            logEntries: logEntries,
            deeplinkEntries: deeplinkEntries,
            onPhaseChange: onPhaseChange
        )

        await onPhaseChange(.writingFile)
        try? await Task.sleep(for: .milliseconds(500))

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd_HHmmss"
        let dateString = dateFormatter.string(from: Date())
        let fileName = "inspector_report_\(dateString).md"
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)

        do {
            try content.write(to: tempURL, atomically: true, encoding: .utf8)
            return tempURL
        } catch {
            return nil
        }
    }

    private static func buildMarkdown(
        networkEntries: [NetworkEntry],
        logEntries: [LogEntry],
        deeplinkEntries: [DeeplinkEntry],
        onPhaseChange: @MainActor @Sendable @escaping (ExportPhase) -> Void
    ) async -> String {
        var md = ""

        await onPhaseChange(.deviceInfo)
        md += generateHeader(
            networkCount: networkEntries.count,
            logCount: logEntries.count,
            deeplinkCount: deeplinkEntries.count
        )
        try? await Task.sleep(for: .milliseconds(500))

        await onPhaseChange(.networkLogs)
        md += generateNetworkSection(networkEntries)
        try? await Task.sleep(for: .milliseconds(500))

        await onPhaseChange(.consoleLogs)
        md += generateConsoleSection(logEntries)
        try? await Task.sleep(for: .milliseconds(500))

        await onPhaseChange(.deeplinkLogs)
        md += generateDeeplinkSection(deeplinkEntries)
        try? await Task.sleep(for: .milliseconds(500))

        md += "\n---\n\n"
        md += "> Report generated by **WarwareInspector**\n"

        return md
    }

    private static func generateHeader(
        networkCount: Int,
        logCount: Int,
        deeplinkCount: Int
    ) -> String {
        let bundle = Bundle.main
        let appVersion = bundle.infoDictionary?["CFBundleShortVersionString"] as? String ?? "Unknown"
        let buildNumber = bundle.infoDictionary?["CFBundleVersion"] as? String ?? "Unknown"
        let exportDate = Date().formatted(date: .abbreviated, time: .standard)

        var md = "# Inspector Report\n\n"
        md += "> Generated: \(exportDate)\n"
        md += "> App: v\(appVersion) (\(buildNumber))\n\n"

        md += "## Table of Contents\n\n"
        if networkCount > 0 { md += "- [Network](#network) (\(networkCount) requests)\n" }
        if logCount > 0 { md += "- [Console Logs](#console-logs) (\(logCount) logs)\n" }
        if deeplinkCount > 0 { md += "- [Deeplinks](#deeplinks) (\(deeplinkCount) links)\n" }
        md += "\n"

        return md
    }
}
